Anthony
squire40/csharp-koans pull request #18
Opened 2019-02-18 17:03 UTC by achetcu

About Nulls finished. Am I suppose to close the old pull request before push my changes for next time?

2019-02-18 20:41 UTC, squire40 requested changes
Type out exception message.

2019-02-18 20:41 UTC, squire40 commented on TheKoans/AboutNull.cs
> +                Assert.AreEqual(exception.Message, exception.Message, "If you're still unsure, take a look at the name of this method...");
Actually type the exception message.

2019-02-18 20:41 UTC, squire40 commented on TheKoans/AboutNull.cs
> +                Assert.AreEqual(exception.Message, exception.Message, "If you're still unsure, take a look at the name of this method...");
Object reference not set to an instance of an object.

2019-02-24 17:45 UTC, closed without merging

2019-02-24 17:45 UTC, achetcu commented
All updated